main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2

  - name: "Contact"
    url: "/#contact"
    weight: 3

buttons:
  - name: "Get Started"
    url: "/#contact"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2

  - name: "Contact"
    url: "/#contact"
    weight: 3
