main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2

  - name: "About"
    url: "/#about"
    weight: 3

  - name: "Contact"
    url: "/#contact"
    weight: 4

buttons:
  - name: "Get Started"
    url: "/#contact"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2

  - name: "About"
    url: "/#about"
    weight: 3

  - name: "Contact"
    url: "/#contact"
    weight: 4
